
name: synthetic-experiments

data:
# Data parameters
  size_list: [[10, 10, 10, 10]]
  d_list: [[2, 2, 2, 2]]

noise:
# Noise parameters
  SNR: [-1, 5, 10]

model:
  geoTL:
    gamma: [0.01,0.1,1,10]
    theta: [0.01,0.1,1,10]