
name: synthetic-experiments

data:
# Data parameters
  size_list: [[10, 10, 10, 10]]
  d_list: [[2, 2, 2, 2]]

noise:
# Noise parameters
  SNR: [-1, 0, 1, 5, 10, 15]

model:
  geoTL:
    gamma: [1]
    theta: [0.01,0.05,0.1,0.5,1,5,10]