
name: synthetic-experiments

data:
# Data parameters
  size_list: [[10, 10, 10, 10]]
  d_list: [[2, 2, 2, 2]]

noise:
# Noise parameters
  SNR: [0.1, 0.2, 0.3, 0.4, 0.5]
  noise_type: 'gross'

model:
  geoTL:
    gamma: [0.01,0.1,1,10]
    theta: [0.01,0.1,1,10]