
name: synthetic-experiments

data:
# Data parameters
  size_list: [[10, 10, 10, 10]]
  d_list: [[2, 2, 2, 2]]

noise:
# Noise parameters
  SNR: [-1, 0, 1, 3, 5, 7, 9, 10]
  noise_type: 'AWGN'

model:
  geoTL:
    gamma: [0.9,1,3,5]
    theta: [0.9,1,3,5]